language: node_js
node_js:
- 12
- 10
- 8
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: jakob.voss@gbv.de
  api_key:
    secure: FS9PwLqp5O3QLpJAyTwgwufVsNIh8aCaGs6nCJwHq+tNgwamvtOJFSUs+KP98W0WUd1/Bq5vGUHvn5UpFanaDqIxBv5mIrrSKAVWJAeufLaKbA/LehtXraHN/c8RCBel1pWU3NOxypRqOC5xQgbKLE2lP9Qo69dQP952y0Z4jluXuRh1iZgiZZR+ikS7sTDu2JcoJRs+3eVvBqBF+PQ/2rin+VDHpFhqDcSqSRcFn0lVHTsi/pedeFdVDALK+Hkyo2ZZlOAodwtLk7wlnBtIV1Pws9W9LYO3dk9Blv3JwhvlxocDP9jmrkQ7zHKEZYQOnJuTWNM0bexm95ZY5p6YeO7gij9xrfw3E61zD0y4cOqNIAWBWvAhC2mXxeEKiGu9iNzT+/U89yoPdCrIEVyWKQ0H95MgxHgXXf/NJMHM3/OGWoXnIncpW+kz5WcBeGHZipo//IZIJFRn18jBZvdZRnI5T6yRAY1bVWVtJXOF4JHH0O95i9Oiiee0t2rZL+zgI1zJTR7j56R2h/HyU5hx19HisxvhjoPq3pp9hIFfXu2pLbnj29mc40kcdpBFt7LicXPFkPlujROAL1maVe46eyksIeIpVVGhJZHkBjz0T9AqYnNEN2V/zrvHR+LctL1TdYCgKRQaqElZlRWsfd8IscKB9/7tFWYW1uOp88AaKyY=
  on:
    tags: true
    repo: gbv/jskos-validate
