language: node_js
node_js:
- 14
- 12
- 10
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: jakob.voss@gbv.de
  api_key:
    secure: eBvunjrbXCkTSL7Wow/Oer3FkbCzm0oIjZj47RpEKnIiFX2N35fkPgamFUUfi/cPHquim85PIHFZZmAUGM/UByYmg8rt2Kgf1le5Yjv63BMANMfRQLfhgGYDpEu7HYX3Fe3DKhVfd+FqRTq7EpaEQz6ekUU/eEOlolrC3k1fK4sZk6Hx2o5uxug0l00jixB81O7cHTX25gpWZEnWz1RniEMdXzbkaCl1XmnJ0ixXs9vQ8kNmy/oRZKpWrNX6+e/vwJDnjz6eS4D5ZHR5UGuB86+BUpv+Na1TEdoA/9Db7nHUWlFh12Mc2352ZmYGxDj80n4mT5viZ1gTHtvtNrGXv2Q86J1A/Ci0d9CGYVtP0FTnRhHy3vV1r1Jj/kQtAkYHpz3ZLK1TgEwQBF+keibvUT5pydrKtO1RJ+JuroKungsKRIOw015j64AkSoy6VmraUmS7dvVzNXRl63eRd56Ybn3wVDQuRrHK1Exni+e38Yr+O36z6dLmrRfNey26OEo4b6LepiIcIl0RMSPSUq4W+Nz8Y0yDGnW5UcWphNafJuJr/GdUS15d8WG0LEQO2mB6njRtejQlhnBaYd+q+zaJWdrxctHmBX6sGqvYUjqAwAfE2YkDU+ng6KhN4dk+uFZOOqbLpRSxWMSCNUlpmP11sgq9PRFUsbjGQzLX6VvQDXQ=
  on:
    tags: true
    repo: gbv/jskos-validate
