# This workflow will release a package at npmjs and at GitHub releases

name: Release

on:
  push:
    tags:
      - v*

jobs:
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org
    - name: Install and build
      run: |
        npm ci
        npm run build
    - name: Publish to npm
      run: npm publish --provenance --access=public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
